# -*- coding: utf-8 -*-
"""SVC TUTORIAL .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1etLBC8lzefRpfcIU--qSAdWnNr9kVdub
"""

from matplotlib.pyplot import*
x=(11,12,15,22,32)
y=(22,36,54,81,99)
plot(x,y,marker='o',color='k',linewidth='5',markersize=15,markeredgecolor='red',linestyle='dashed')
show()

from matplotlib.pyplot import*
a=(11,25,37,40,59)
b=(14,55,70,89,111)
c=(15,18,25,32,100)
e=(35,58,70,85,130)
f=(50,60,75,88,99)
g=(65,89,99,100,120)
plot(f,g)
plot(a,b)
plot(c,e)
xlabel('Time')
ylabel('velocity')
title('SVC Tutorial-1')
show()

from matplotlib.pyplot import*
a=(10,22,38,40,57)
b=(25,29,36,45,55)
c=(17,35,70,99,155)
d=(57,71,95,116,132)
plot(a,d)
plot(b,c)
xlabel('velocity')
ylabel('time')
plot(a,d,b,c,color='k',marker='o')
show()

from matplotlib.pyplot import*
from numpy import*
x=arange(-50,50)
xlabel('x')
ylabel('y')
title('Numpy')
y=x**2
y1=-x**2
plot(x,y)
plot(x,y1)
plot(x,-x)
p=(0,0)
q=(-8000,8000)
plot(p,q)
show()

from matplotlib.pyplot import*
from numpy import*
x=linspace(1,-50,100)
y=sin(x)
plot(x,y)


y=cos(x)
plot(-x,y)
show()

y=tan(x)
plot(x,y)
show()

from matplotlib.pyplot import*
from numpy import*
x=(-10,10)
y=(-20,20)
plot(x,y)
show()

from matplotlib.pyplot import*
from numpy import*
x=arange(0,8.1,0.1)
print(x)
v=4*x**3-92*x**2+480*x
print(v)
plot(v)
show()

from matplotlib.pyplot import*
from numpy import*
t=arange(0,11)
h=449.36+0.96*t-4.90*t**2
xlabel('time (in sec)')
ylabel('height (in meter')
plot(t,h)
show()
print(t)
print(h)

from matplotlib.pyplot import* 
from numpy import*
t=arange(0,20)
h=-25*cos((2*180/20)*t)+30
xlabel('time (insec)')
ylabel('height (in feet)')
plot(t,h)
show()

from matplotlib.pyplot import*
from sympy import*
x=Symbol('x')
l=limit((2*sin(x)-sin(2*x))/x**3,x,0)
print(l)

from sympy import*
x=Symbol('x')
a=Symbol('a')
b=Symbol('b')
l=limit((a**x-b**x)/x,x,0)
print(l)

from sympy import*
x=Symbol('x')
a=Symbol('a')
b=Symbol('b')
l=limit((a**x-b**x)/x,x,0)
print(l)

from sympy import*
x=Symbol('x')
limit((log(x)/cot(x)),x,0)

from turtle import*
speed(10)
color('cyan')
bgcolor('black')
b = 200
while b> 0:
  left(b)
  forward(b * 3)
  b = b - 1
  show()